/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBoule {
        "boule": boolean;
        "checked": boolean;
        "extra": boolean;
        "number": number;
    }
    interface AppLotoForm {
        "boules": number[];
        "extras": number[];
        "nbBoules": number;
        "nbExtras": number;
    }
    interface AppLotoSummary {
        "boules": number[];
        "extras": number[];
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppBouleElement extends Components.AppBoule, HTMLStencilElement {
    }
    var HTMLAppBouleElement: {
        prototype: HTMLAppBouleElement;
        new (): HTMLAppBouleElement;
    };
    interface HTMLAppLotoFormElement extends Components.AppLotoForm, HTMLStencilElement {
    }
    var HTMLAppLotoFormElement: {
        prototype: HTMLAppLotoFormElement;
        new (): HTMLAppLotoFormElement;
    };
    interface HTMLAppLotoSummaryElement extends Components.AppLotoSummary, HTMLStencilElement {
    }
    var HTMLAppLotoSummaryElement: {
        prototype: HTMLAppLotoSummaryElement;
        new (): HTMLAppLotoSummaryElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-boule": HTMLAppBouleElement;
        "app-loto-form": HTMLAppLotoFormElement;
        "app-loto-summary": HTMLAppLotoSummaryElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppBoule {
        "boule"?: boolean;
        "checked"?: boolean;
        "extra"?: boolean;
        "number"?: number;
        "onToggle"?: (event: CustomEvent<void>) => void;
    }
    interface AppLotoForm {
        "boules"?: number[];
        "extras"?: number[];
        "nbBoules"?: number;
        "nbExtras"?: number;
        "onUpdate"?: (event: CustomEvent<{ boules: number[]; extras: number[] }>) => void;
    }
    interface AppLotoSummary {
        "boules"?: number[];
        "extras"?: number[];
        "onBouleDelete"?: (event: CustomEvent<number>) => void;
        "onExtraDelete"?: (event: CustomEvent<number>) => void;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-boule": AppBoule;
        "app-loto-form": AppLotoForm;
        "app-loto-summary": AppLotoSummary;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-boule": LocalJSX.AppBoule & JSXBase.HTMLAttributes<HTMLAppBouleElement>;
            "app-loto-form": LocalJSX.AppLotoForm & JSXBase.HTMLAttributes<HTMLAppLotoFormElement>;
            "app-loto-summary": LocalJSX.AppLotoSummary & JSXBase.HTMLAttributes<HTMLAppLotoSummaryElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
